Projekt/Models/Usterki.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Projekt.Models
{
    public class Usterki
    {
        [ScaffoldColumn(false)]
        [Key]
        public int idUsterki { get; set; }

        [Display(Name = "Rodzaj/typ usterki")]
        public Typ typUsterki { get; set; }

        [Display(Name = "Opis")]
        public string opis { get; set; }

        [Display(Name = "Data zgłoszenia")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? dataZgloszenia { get; set; }
        
        [Display(Name = "Prześlij plik")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Miejsce")]
         public string wspolrzedne { get; set; }
        [ScaffoldColumn(false)]
        public int? status { get; set; }
    }
    public enum Typ
    {
        hydrauliczne,
        drogowe,
        elektryczne,
        inne
    }
}

Projekt/Controllers/UsterkiController.cs
using Projekt.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projekt.Controllers
{
    public class UsterkiController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult ListaUsterek()
        {
            return View(db.usterki.ToList());
        }
        [Authorize]
        public ActionResult DodajZgloszenie()
        {
            Usterki usterka = new Usterki();
            return View(usterka);
        }
        [Authorize]
        [HttpPost]
        public ActionResult DodajZgloszenie(Usterki usterka)
        {
            string fileName = Path.GetFileNameWithoutExtension(usterka.ImageFile.FileName);
            string extension = Path.GetExtension(usterka.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            usterka.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            usterka.ImageFile.SaveAs(fileName);
            //if (!ModelState.IsValid)
            //{
            //    return View(usterka);
            //}
            //else
            //{
                ViewBag.Message = "Dodano zgłoszenie";
                db.usterki.Add(usterka);
                db.SaveChanges();
                return View();
         //   }
        }
    }
}

Projekt/Views/Usterki/DodajZgloszenie.cshtml
@using Projekt.Models
@model Usterki
@{
    ViewBag.Title = "Dodaj";
}

<h2>Dodaj</h2>
<span style="font-size: 15px; color: green;">
    <h3>@ViewBag.Message</h3>
</span>

<!DOCTYPE html>
<body>
    <div id="posty">
        <font size="3">
            @using (Html.BeginForm("DodajZgloszenie", "Usterki", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <span class="display-name">@Html.DisplayNameFor(model => Model.typUsterki)</span>
                <div>
                    @Html.DropDownListFor(m => m.typUsterki, new SelectList(Enum.GetValues(typeof(Typ))), "Wybierz rodzja")
                    @Html.ValidationMessageFor(model => Model.typUsterki, "", new { @class = "text-danger" })
                </div>
                <span class="display-name">@Html.DisplayNameFor(model => Model.opis)</span>
                <div>
                    <span class="textboxcontent">@Html.TextAreaFor(model => Model.opis, new { @style = "color: #000000" })</span>
                    @Html.ValidationMessageFor(model => Model.opis, "", new { @class = "text-danger" })
                </div>
                <div>
                    <span class="display-name">@Html.DisplayNameFor(model => Model.ImagePath)</span>

                    <input type="file" name="ImageFile" />
                </div>
                <br />
                <br />


                <div>
                    <input id="Submit1" type="submit" value="Utwórz" style="color: black;" />
                </div>


            }
        </font>
    </div>
</body>

Projekt/Views/Usterki/ListaUsterek.cshtml
@model IEnumerable<Projekt.Models.Usterki>
@{
    ViewBag.Title = "Lista zgłoszonych usterek";
}
<style type="text/css">

    .bezramki {
        border-top: 0;
    }
</style>
<h2>Lista zgłoszonych usterek</h2>

@foreach (var item in Model)

{
    <div class="leftcolumn">
        <div class="card mb-4">

            <div class="card-body">
                <h2 class="card-title"> @Html.DisplayFor(modelItem => item.typUsterki)</h2>
                <p class="card-text">@Html.DisplayFor(modelItem => item.opis)</p>
                @*<a href="#" class="btn btn-primary">Read More &rarr;</a>*@
            </div>
            <img class="card-img-top" src="@Url.Content(item.ImagePath)" alt="Card image cap" style="width:150px;height:150px;">
        </div>
        <hr />
    </div>
   
}